substitutions:
  devicename: weatherstation
  upper_devicename: Weatherstation


esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2
  build_path: ./build/${devicename}

packages:
  wifi: !include common_wifi.yaml
  network: !include ws_network.yaml
  busses: !include ws_busses.yaml

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

ota:

sensor:
  - platform: sds011
    pm_2_5:
      name: "pm 25"
    pm_10_0:
      name: "pm 10"
    update_interval: 5min

  - platform: bme280
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    address: 0x76
    update_interval: 60s

  - platform: bh1750
    name: "Illuminance 1"
    address: 0x23
    update_interval: 60s
    
  # - platform: tcs34725
  #   red_channel:
  #     name: "Red"
  #   green_channel:
  #     name: "Green"
  #   blue_channel:
  #     name: "Blue"
  #   clear_channel:
  #     name: "Clear"
  #   illuminance:
  #     name: "Illuminance 2"
  #     filters:
  #       - calibrate_linear:
  #           # Map 0.0 (from sensor) to 0.0 (true value)
  #           - 0.0 -> 0.0
  #           # - 1.4 -> 782.8
  #           # - 2.4 -> 1441.7
  #           # - 5.6 -> 3751.7
  #           - 7.9 -> 4998.3
  #           # - 34.9 -> 29300.7
  #           - 38.4 -> 29799.2
  #   color_temperature:
  #     name: "Color Temperature"
  #   gain: 1x
  #   integration_time: 2.4ms
  #   address: 0x29
  #   update_interval: 60s


