sensor:
  - platform: dht
    pin: $dhta_pin
    temperature:
      name: ${devicename_upper} Temperature
      id: "local_t"
    humidity:
      name: ${devicename_upper} Humidity
      id: "local_h"
    update_interval: 60s

binary_sensor:
  - platform: template
    name: ${devicename_upper} Heater
    id: heating
    lambda: |-
      if ( id(local_t).state > (id(target_t).state+0.3) ) {
        return false;
      }
      else if (id(local_t).state < (id(target_t).state-0.3)) {
        return true;
      }
      else {
        return {};
      }

  - platform: template
    name: ${devicename_upper} Humidifier
    id: humidifying
    lambda: |-
      if ( id(local_h).state > (id(target_h).state+2) ) {
        return false;
      }
      else if (id(local_h).state < (id(target_h).state-2)) {
        return true;
      }
      else {
        return {};
      }
